apiVersion: v1
kind: Secret
metadata:
  name: chobu-secret
  namespace: chobu
type: Opaque
stringData:
  JWT_SECRET: super-secret
  BACKEND_DATABASE_URL: postgresql+psycopg://chobu:chobu@postgres:5432/chobu
  INFO_DATABASE_URL: postgresql+psycopg://chobu:chobu@postgres:5432/chobu
