CREATE TABLE IF NOT EXISTS attendance_resources (
  id UUID PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(1024),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
