apiVersion: v1
kind: Service
metadata:
  name: chobu-backend
  namespace: chobu
spec:
  selector:
    app: chobu-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
