apiVersion: v1
kind: ConfigMap
metadata:
  name: chobu-config
  namespace: chobu
data:
  APP_ENV: "development"
  APP_PORT: "3000"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "chobu"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
